services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to_do_list_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    restart: unless-stopped