services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: to_do_list_app
    command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app
    restart: unless-stopped
